### PR TITLE
Use seeds to get deterministic behavior in unit tests and examples

### PR DESCRIPTION
**Pull request by tovrstra**
This PR fixes issue #12. There may be more tests that should use the `numpy_seed` context manager but most should be covered. Many randomized tests do not have (nor need) this fix. Applying this fix to all of them is probably overkill.

Please, also review the extra documentation.

### CODE REVIEW

**Comment by matt-chan** [comment]
Looks good to me. Merging.

**Comment by tovrstra** [comment]
It seems that the build failed after merging because the merge through the github web interface committed with author and committer "M <matt-chan@users.noreply.github.com>". Are these the settings of your github account, or does github generate these weird author names and e-mail addresses on the fly?

**Comment by matt-chan** [comment]
The email is generated on the fly. It happens if you ask github to keep
your email non-public. The unfortunate side effect is that the github
profile uses the same settings.

I've changed the setting now and updated my github profile to match my
laptop's git author settings. And the world can see it. Oh well.

I'm not sure how to fix the merge that happened already though. Maybe
there's a way to amend the commit through the web interface. Otherwise it
means we have to do a force push?
On Thu, May 26, 2016 at 10:39 PM Toon Verstraelen <notifications@github.com>
wrote:

> It seems that the build failed after merging because the merge through the
> github web interface committed with author and committer "M
> matt-chan@users.noreply.github.com". Are these the settings of your
> github account, or does github generate these weird author names and e-mail
> addresses on the fly?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/theochem/horton/pull/26#issuecomment-222046785>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA_-NUL9sSAXB2KuQM0-VrTq_I2Osy2Yks5qFllTgaJpZM4ImLga>
> .
>
-- 
Matt

Sent from my phone

**Comment by tovrstra** [comment]
I understand now. Making your e-mail public could indeed be a problem. Most researchers have such a public e-mail, typically the university e-mail address. That is usually the one they use as corresponding author on papers and is bound to become public at some point in time.

The only way to fix this is by force push, which is a bit ugly but nothing to really worry about. I've tried to avoid situations where the tests could fail after merging a PR that passed but didn't think of this one. I'll take care of it. (Can you check with Paul if his settings may also cause this problem?)

**Comment by tovrstra** [comment]
Tests are running. fingers crossed ...

**Comment by tovrstra** [comment]
... they passed.

**Comment by matt-chan** [comment]
Sorry Toon. It still does the no-reply email even after setting "show my
email as chanmhy".... I've got the name showing up properly now though. I
hope this doesn't make the travis build fail again...

I'll look into how to get the email working properly...

On Fri, 27 May 2016 at 00:11 Matthew Chan <talcite@gmail.com> wrote:

> The email is generated on the fly. It happens if you ask github to keep
> your email non-public. The unfortunate side effect is that the github
> profile uses the same settings.
>
> I've changed the setting now and updated my github profile to match my
> laptop's git author settings. And the world can see it. Oh well.
>
> I'm not sure how to fix the merge that happened already though. Maybe
> there's a way to amend the commit through the web interface. Otherwise it
> means we have to do a force push?
> On Thu, May 26, 2016 at 10:39 PM Toon Verstraelen <
> notifications@github.com> wrote:
>
>> It seems that the build failed after merging because the merge through
>> the github web interface committed with author and committer "M
>> matt-chan@users.noreply.github.com". Are these the settings of your
>> github account, or does github generate these weird author names and e-mail
>> addresses on the fly?
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/theochem/horton/pull/26#issuecomment-222046785>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AA_-NUL9sSAXB2KuQM0-VrTq_I2Osy2Yks5qFllTgaJpZM4ImLga>
>> .
>>
> --
> Matt
>
> Sent from my phone

-- 
Matt

Sent from my phone

**Pull request merged**
