### PR TITLE
s/kation/cation/g

### LINKED ISSUE #128: Cation with a 'C'
Just change the occurrences of Kation to Cation.

### PR DESCRIPTION
**Pull request by matt-chan**
Fixes #128

### CODE REVIEW

**Comment by tovrstra** [comment]
@matt-chan Do you see why the tests are not running?

**Comment by tovrstra** [comment]
Can you ammend (with nothing new) and for push to trigger the tests?

**Comment by matt-chan** [comment]
There we go. Not sure what happened...

**Comment by tovrstra** [comment]
Looks good! Merging...

**Pull request merged**
