### PR TITLE
using python -m coverage/pylint/pydocstyle in trapdoor #107

### PR DESCRIPTION
**Pull request by sfias**
I changed the commands coverage/pylint/pydocstyle to python -m coverage/pylint/pydocstyle.

### CODE REVIEW

**Comment by tovrstra** [comment]
@sfias Can you briefly motivate the change? Could it be that the directory with the coverage executable is not in your ${PATH}?

**Comment by tovrstra** [comment]
ok, I saw the issue #107 . I guess this a matter of setting the PATH. I'm not sure how you installed coverage? If done with Pip on Linux, you need to add `${HOME}/.local/bin` to the PATH. Something similar may be needed for OSX.

**Comment by sfias** [comment]
hmm, I can't locate any executables... pip installed it in /Users/Stijn/Library/Python/2.7/lib/python/site-packages. I installed coverage using macports, and that places an executable in /opt/local/bin/ , which is in my PATH, but it's called coverage-2.7... I guess I can make a symbolic link... and do te same for pylint, but there doesn't seem to ba a port for pydocstyle...

**Comment by tovrstra** [comment]
Could you try: `sudo port select --set coverage coverage27`? That is the official way to select a python package for a specific python version to become the default. (I can't test it here, but similar commands are needed to select the right version of nosetests etc.)

Executables installed by Pip seem to go into weird places like `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/`. See the following bug reports for more details:

- https://github.com/pypa/pip/issues/113
- https://trac.macports.org/ticket/50058

I'm not sure why these still aren't fixed. Does this help?

**Comment by sfias** [comment]
sudo port select --set coverage coverage-2.7 nor sudo port select --set coverage coverage27 work, I don't know why, but it sais failed: The specified group 'coverage' does not exist. 
There is a coverage executable in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ (which was in my path, but still it didn't work, which is weird because the other packages work fine) but nothing for pylon or pydocstyle.

**Comment by sfias** [comment]
Found it!
it was in /Users/Stijn/Library/Python/2.7/bin , which was not in my PATH... :) It should work ok now... Sorry for the trouble

**Comment by tovrstra** [comment]
Good. I'm glad it is fixed. I'm a bit reluctant to merge the PR because the right solution is to set the PATH variable. That can unfortunately be non-trivial. There were similar discussions with Mac users about a year ago but they seem to have disappeared.

I'll close the PR and the issue for now. If something similar comes up in future, feel free to make a new issue.

**Comment by matt-chan** [comment]
Can we update the documentation for OS X users to add the path?

**Comment by sfias** [comment]
Now that I've figured it out, I can write something for the documentation if you like...

**Comment by tovrstra** [comment]
We may already have it: http://theochem.github.io/horton/user_download_and_install_troubleshooting.html

Maybe we should refer to this from the Mac install page? PR certainly welcome.

It is not clear to me how general this problem is. Not all mac users seem to have this problem, which is weird because one would expect it to be a rather well defined OS? I'm a bit puzzled.

**Comment by sfias** [comment]
I'm not sure, but my guess it might be because I copied the command from the HORTON manual, with the --user, so it ended up in /Users/Stijn/Library/Python/2.7/bin, which wasn't in my PATH yet. I think I installed all my previous packages with pip without the --user, putting it elsewhere but in a location included in my PATH ( /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ , I think) Anyway, it works now... I'll look at the documentation and may reference to http://theochem.github.io/horton/user_download_and_install_troubleshooting.html in http://theochem.github.io/horton/user_download_and_install_mac.html

**Comment by tovrstra** [comment]
OK, that makes sense. Your experience with the `--user` option is analogous to what we have in Linux. For that reason, the Linux install manual contains a section "Runtime configuration". See http://theochem.github.io/horton/user_download_and_install_linux.html#runtime-configuration

We have something similar for Mac: http://theochem.github.io/horton/user_download_and_install_mac.html#runtime-configuration

I guess that section would solve the problem, or not?

**Pull request closed without merging**
