### PR TITLE
New script to update website

### PR DESCRIPTION
**Pull request by tovrstra**
This takes care of another part of issue #68:

- `updatesite.py` replaces `updatesite.sh`. It can handle different documentation versions and it also writes and index.html with an overview of them. 
- `doc/confg.py` and `doc/releasinfo.py` are modified to write out the relevant data into `doc/releaseinfo.json`. That file is used to generate index.html.
- A few other minor related corrections.

The result can be previewed here: 

- https://tovrstra.github.io/horton/
- https://tovrstra.github.io/horton/latest/

### CODE REVIEW

**Comment by tovrstra** [comment]
Ready for review...

**Comment by matt-chan** [comment]
Looks good to me. I'd wonder about the idea of alpha releases though. Doesn't master already take care of that?

**Comment by tovrstra** [comment]
Good point. I would like to have alpha releases because it facilitates the installation of development versions, e.g. with EasyBuild. Putting (increasing) version numbers on alpha releases is convenient. E.g., it is clear that horton-2.1.0a1 is older than horton-2.1.0a4. (We tend to install a lot of development versions on our cluster, keeping several development versions available with environment modules.)

**Comment by matt-chan** [comment]
Okay, sounds good!

Matt

**Pull request merged**
