### PR TITLE
Fix fedora support

### PR DESCRIPTION
**Pull request by tovrstra**
These are rather trivial changes that fix issues #21 and #22.

### CODE REVIEW

**Comment by tovrstra** [comment]
There is more to come... Please wait with merging.

**Comment by tovrstra** [comment]
The above commits also do the following:

- Fix issue #62 
- Fix issue #63 
- Fix issue #52 
- Make `tools/harmonics.py` and `tools/test_harmonics.py` compatible with Sympy 1.0, which is in Fedora 24.
- Fix broken geminals test on 32 bit Fedora 24.

**Comment by tovrstra** [comment]
Ready for review

**Comment by tovrstra** [comment]
Fedora 24 has sufficiently recent packages for sphinx, sphinx_rtd_theme and breathe, so we don't need pip anymore for that part.

**Comment by matt-chan** [comment]
Should the initial guess be changed to 0.11 in test geminals?

Everything else looks good!

**Comment by tovrstra** [comment]
I was also surprised by the 0.11 change but it was necessary on i686. The geminals code is extremely non-robust. I want get rid of it, rather sooner than later.

**Comment by tovrstra** [comment]
This is ready to be merged for me. I'll make a new issue for remaining things to be fixed for fedora 24.

**Comment by tovrstra** [comment]
P.S. I can confirm that the 0.11 problem is also present on ubuntu 16.04 i686.

**Pull request merged**
