### PR TITLE
Fix mistakes in MANIFEST.in

### PR DESCRIPTION
**Pull request by tovrstra**
This fixes some missing lines in the MANIFEST.in file, as in e.g. #231.

### CODE REVIEW

**Comment by tovrstra** [comment]
@HenriqueCSJ: can you give the following archive a try? [horton-2.0.2.tar.gz](https://github.com/theochem/horton/files/1054202/horton-2.0.2.tar.gz) Thanks.

**Comment by HenriqueCSJ** [comment]
Hi, thank you for the quick action on taking care of this.
It still fails:
```
In file included from ./horton/gbasis/ints.h:26:0,
                 from horton/gbasis/ints.cpp:30:
/usr/include/libint2.h:32:28: fatal error: libint2_params.h: No such file or directory
 #include <libint2_params.h>
                            ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```
Probably because the file is in a slightly different directory:
```
[root@site horton-2.0.2]# locate libint2_params.h
/usr/include/libint2/libint2_params.h
```

**Comment by tovrstra** [comment]
New attempt: [horton-2.0.2.tar.gz](https://github.com/theochem/horton/files/1057728/horton-2.0.2.tar.gz)

**Comment by tovrstra** [comment]
Note that this is just a temporary solution and that setup.cfg files should be replaced by something more robust in future. See #234

**Comment by HenriqueCSJ** [comment]
Here we go.
```
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from horton/meanfield/cext.cpp:449:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
horton/meanfield/cext.cpp: In function ‘PyObject* __pyx_pf_6horton_9meanfield_4cext_12LibXCWrapper_4refs___get__(__pyx_obj_6horton_9meanfield_4cext_LibXCWrapper*)’:
horton/meanfield/cext.cpp:2088:74: error: cannot convert ‘func_reference_type* const*’ to ‘const char*’ for argument ‘1’ to ‘PyObject* PyString_FromString(const char*)’
   __pyx_t_1 = __Pyx_PyBytes_FromString((__pyx_v_self->_func.info[0]).refs); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 104, __pyx_L1_error)
                                                                          ^
error: command 'gcc' failed with exit status 1
```

**Comment by tovrstra** [comment]
Fedora 25 only has packages for LibXC 3.0, which is not compatible with LibXC 2.x. Can you try to compile the 2.2.2 version in the HORTON source tree by running the script

    ./tools/qa/install_libxc-2.2.2.sh 

If this works, I'll update the install docs. It is currently not mentioned.

**Comment by HenriqueCSJ** [comment]
Sorry for my delay. I'll give it a try ASAP.

**Comment by tovrstra** [comment]
Ping. Any news?

**Comment by tovrstra** [comment]
I could test it myself in the meantime and I get exactly the same error on Fedora 25 when trying to build against the LibXC version that is shipped with Fedora. I'll also test with Fedora 26 beta, probably has the same issue. This should at least be documented. Eventually we'll use the newer LibXC in HORTON but not for the next release.

**Comment by tovrstra** [comment]
See also #224.

**Pull request merged**
