### PR TITLE
Fixes for installation on Ubuntu 16.04 and Fedora 24

### PR DESCRIPTION
**Pull request by tovrstra**
This PR fixes the following:

- Issue #23 
- Issue #24 
- issue #71 
- Initial guesses for the geminals tests should now work all (practically) all distributions.

### CODE REVIEW

**Comment by matt-chan** [comment]
Should we add fedora 23 into dependencies.txt as well?

**Comment by tovrstra** [comment]
Fedora 22 and 23 turn out to be the same in terms of dependencies. In the documentation, they are always mentioned together, so there was no need to define separate packages for fedora 22 and 23. The situation is similar for ubuntu 14 and 15. See for example, `doc/user_download_and_install_linux.rst.template`. 

As soon as any of the scripts that uses `dependencies.txt`, needs such information separately for every supported distribution, I would add it. For now, it is not really needed yet.

**Comment by matt-chan** [comment]
Great! Everything looks good then. Merging

**Comment by tovrstra** [comment]
Thanks for reviewing!

**Pull request merged**
