### PR TITLE
[DO NOT MERGE] Iso_io

### PR DESCRIPTION
**Pull request by matt-chan**
_Just starting this PR a bit earlier so I can keep track of API changes._

This PR contains an isolated io module. 

**There are API changes.**

Deprecations:
- LockedH5 and the internal H5 file format have been removed.

Parameters:
- The vasp ``dump_poscar`` routine now requires ``data`` to contain an attribute ``cell_frac`` which contains the return value of the cell.to_frac function.

Return values: 
- The ``obasis`` attribute no longer contains an instance of obasis. Rather it contains a dict of all elements necessary to instantiate GOBasis. Simply pass it via GObasis(*obasis.values())
- The ``orb_alpha`` attribute no longer contains an Orbital instance. It has been replaced by four attributes: 
    - ``orb_alpha``: a tuple of (nbasis, nfn). Sufficient to instantiate a Orbital class.
    - ``orb_alpha_coeffs``: formerly Orbitals.coefficients
    - ``orb_alpha_energies``: formerly Orbitals.energies
    - ``orb_alpha_occs``: formerly Orbitals.occs
- The ``cell`` attribute is no longer a Cell instance. Rather it contains a numpy array rvecs which is sufficient to instantiate a Cell instance. 
- The ``grid`` attribute no longer contains an UniformGrid instance. It now contains a dict sufficient to instantiate a UniformGrid instance. It can be used via UniformGrid(*grid.values())
- Vasp IOData instances now require a ``gvecs`` attribute to write the coordinates. 

Non-API breaking changes:
- The molden coefficient normalization now uses internal code to calculate the overlap integrals. The dependency on gbasis has been removed.

### CODE REVIEW

**Comment by matt-chan** [comment]
Looks like the overlap code will need to be cython'd after all... cp2k unit tests take 2 minutes alone.

It doesn't look too hard though. 60% of the time is spent in a few simple functions that can be replaced.

horton3

**Comment by tovrstra** [comment]
I took a quick look at the overlap code and don't see very obvious opportunities to speed things up at the Python level. `add_overlap` and its internals seem to be the obvious candidates to move to Cython. The files from CP2K have somewhat weird basis sets but the files are certainly realistic.

**Comment by matt-chan** [comment]
Okay, so it's Cython'd now! Down to 7s for all the unit tests =). It's still somewhat readable I think? It's ready to review @tovrstra

**Comment by FarnazH** [comment]
The isolated io module in this branch is now an independent module with Python 2 & 3 compatibility. Please see: <https://github.com/theochem/iodata>

**Comment by matt-chan** [comment]
@tovrstra, I'm going to close the PR soon since @FarnazH moved it to a new repo. It's easier to review in this format though. Is there anything you'd like changed before I do it?

**Comment by FarnazH** [comment]
I have no more changes at this stage. I think we can continue improving the code in  https://github.com/theochem/iodata repo.

**Comment by matt-chan** [comment]
Closing since it's been moved to https://github.com/theochem/iodata. The code has diverged too much to make changes here feasible.

**Pull request closed without merging**
