### PR TITLE
update installation documentation for MAC

### PR DESCRIPTION
**Pull request by tczorro**
Delete old tedious steps and replace with new concise installation
procedures

### CODE REVIEW

**Comment by tovrstra** [comment]
The old way of installing is still relevant, e.g. when macports is not installing the latest version, etc.

Ideally, we have both procedures in the documentation. There are a few other things in the documentation that should be fixed as well, for which I'll make an issue in a minute.

**Comment by tovrstra** [comment]
@tczorro @matt-chan  : would the following single line result in a proper install of HORTON?

    sudo port install horton

**Comment by tczorro** [comment]
Since openblas(atlas) needs gcc.
So the command should be

sudo port install gcc49 (or other recommanded version higher than 49)
sudo port install horton

Right now, the version of horton on macport is still 2.0.0. I am planning to update it to the latest on theochem/horton/master
For latest version of horton, even without numpy +atlas or numpy +openblas, all the tests are still good.
The only problem is the the new libxc. On macport, libxc 2.2.3 will be forced to use rather then 2.2.2.
It should be fine for 2.0.0 horton. But for latest horton, it leads to a libxc test error.

**Comment by tovrstra** [comment]
Closing this PR because the same problem is solved in #246, in a slightly better way.

**Pull request closed without merging**
