### PR TITLE
Fix install pxd

### PR DESCRIPTION
**Pull request by tovrstra**
This was needed to link external C++ code to C++ code in Horton. (Not the complete solution. I still had to copy over cpp files to the other project. That can only be fixed by making a separate C++ library with all the C++ code from HORTON.)

### CODE REVIEW

**Comment by tovrstra** [comment]
@matt-chan I have no further comments or intentions to change this. It is all yours.

**Comment by tovrstra** [comment]
Some overlapping changes are present in PR #126 but that can be fixed by rebasing at some point.

**Comment by tovrstra** [comment]
I'll rebase to resolve the merge conflicts...

**Comment by tovrstra** [comment]
There are relatively few changes left after the rebase. The remaining changes make it possible to use the cdef classes in Cython code in other projects.

**Comment by matt-chan** [comment]
Okay, looks good. Merging!

**Pull request merged**
