### PR TITLE
Remove install docs for outdated linux distros

### PR DESCRIPTION
**Pull request by tovrstra**
We're no longer going to support Fedora 20, Fedora 21, Ubuntu 12.04. Fixes issue #75

### CODE REVIEW

**Comment by matt-chan** [comment]
Hmm. The unit test for horton.espfit.test.test_cost.test_esp_cost_solve fails?

**Comment by tovrstra** [comment]
This is a test that uses random numbers. I haven't seen it break before. Even if it is rare, it is best to apply the `numpy_seed` solution to all esp_fit tests. I'll take care.

**Comment by tovrstra** [comment]
These failing tests should never occur again. I've also cleaned up these tests and notices several small issues in the QA scripts. All should be fine now.

**Comment by matt-chan** [comment]
Looks good! Thanks Toon!

**Pull request merged**
