### PR TITLE
Fix missing things related to windows install doc

### PR DESCRIPTION
**Pull request by tovrstra**
Just a few silly fixes.

### CODE REVIEW

**Comment by tovrstra** [comment]
The script `check_whitespace,py` should be updated to only fail on tabs in `.py` files.

**Comment by tovrstra** [comment]
This should be rebased after merging #200.

**Comment by matt-chan** [comment]
Looks good to me. Are you going to get a merge conflict when rebasing though? The check_commits.py script is present in #200 as well.

**Comment by tovrstra** [comment]
Yup, #200 should be merged first, after which I'll rebase this one. (It is in fact already rebased, so git rebase will see that the commits are the same. If there are still conflicts, I'll take care.)

**Comment by tovrstra** [comment]
Just rebased.

**Comment by tovrstra** [comment]
This should be reviewable now. Note: Makefiles must contain tabs, hence the exception.

**Pull request merged**
