### PR TITLE
Fix several QA issues

### PR DESCRIPTION
**Pull request by tovrstra**
The commits contain the following changes:

- Fix issue #53 
- Fix issue #49 
- Fix issue #36 
- It also tests for errors to be fixed in #16
- Better reuse of code to get a list of all source files

### CODE REVIEW

**Comment by tovrstra** [comment]
Some more improvements:
- Trapdoor scripts are now also QA tested.
- Some more adjustments to pylintrc:
    - Exclude C0411 due to false positive
    - Allow dummy variables starting with underscore. This is often useful with multiple loop variables of which some are not used. See for example the usage of `os.walk` in `trapdoor.py`
- Cleanups in trapdoor code.

**Comment by matt-chan** [comment]
There's a typo on ln27 of remove_old_wheels.py

**Comment by matt-chan** [comment]
Okay looks good to me! Merging.

**Comment by tovrstra** [comment]
Thanks @matt-chan !

**Pull request merged**
